version: '2.1'
services:
  ml_api:
    build:
      context: ml_api
    volumes:
      - ./ml_api:/app
    depends_on:
      - redis

  web:
    build:
      context: web
    ports:
      - "3334:3334"
    volumes:
      - ./web:/app
    depends_on:
      - ml_api
      - redis
    command: bash -c "python manage.py collectstatic --noinput -c && python manage.py migrate && newrelic-admin run-program gunicorn config.wsgi:application --workers 3 --bind 0.0.0.0:3334"

  redis:
    image: redis:5.0
