version: '2.1'
services:
  ml_api:
    build:
      context: ml_api
    volumes:
      - $PWD/ml_api:/app

  web:
    build:
      context: web
    ports:
      - "3334:3334"
    volumes:
      - $PWD/web:/app

  redis:
    image: redis:5.0
